# Generated by Django 4.2.1 on 2023-05-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('color', models.CharField(max_length=10, verbose_name='Цвет')),
                ('material', models.CharField(max_length=10, verbose_name='Материал')),
                ('size', models.CharField(max_length=4, verbose_name='Размер')),
                ('weight', models.CharField(max_length=3, verbose_name='Масса')),
                ('photo', models.ImageField(default='None', upload_to='photos', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Таблица производителя',
            },
        ),
    ]
