# Generated by Django 4.2.1 on 2023-05-11 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=10, verbose_name='Цвет')),
                ('material', models.CharField(max_length=10, verbose_name='Материал')),
                ('size', models.CharField(max_length=4, verbose_name='Размер')),
                ('options', models.TextField(max_length=1000, verbose_name='Дополнительные свойства')),
            ],
        ),
    ]
